[package]
name = "app"
version.workspace = true
edition.workspace = true
license.workspace = true
default-run = "lemon"

[[bin]]
name = "lemon"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
core_types.workspace = true
source.workspace = true
processing.workspace = true
storage.workspace = true
analysis.workspace = true
report.workspace = true
tui.workspace = true
serde_json.workspace = true
ctrlc.workspace = true
clap.workspace = true
directories.workspace = true
